### ISSUE TITLE
Getting and error ... sqlite3.OperationalError: near ")"

### ISSUE THREAD

**Issue by Nogbit** [simonw/geojson-to-sqlite#16]
I'm attempting to import the following GeoJSON which seems valid to me yet I get this syntax error, which seems to be on table creation, which seems to happen after JSON validation.  I'm at a loss here, any ideas?

command
`geojson-to-sqlite masks.db features data.json --spatialite`

data.json
```
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -96.8131837248802,
              33.0548974593963
            ],
            [
              -96.813183054328,
              33.0548974593963
            ],
            [
              -96.8131837248802,
              33.0548974593963
            ]
          ]
        ]
      }
    }
  ]
}
```

error
```
Traceback (most recent call last):
  File "/usr/local/bin/geojson-to-sqlite", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/geojson_to_sqlite/cli.py", line 34, in cli
    utils.import_features(
  File "/usr/local/lib/python3.8/dist-packages/geojson_to_sqlite/utils.py", line 55, in import_features
    db[table].create(column_types, pk=pk)
  File "/usr/local/lib/python3.8/dist-packages/sqlite_utils/db.py", line 863, in create
    self.db.create_table(
  File "/usr/local/lib/python3.8/dist-packages/sqlite_utils/db.py", line 517, in create_table
    self.execute(sql)
  File "/usr/local/lib/python3.8/dist-packages/sqlite_utils/db.py", line 236, in execute
    return self.conn.execute(sql)
sqlite3.OperationalError: near ")": syntax error
```

**Comment by Nogbit** [comment]
It turns out I did not have a `properties` node in my json. 

working geojson
```
{
  "type": "FeatureCollection",
  "name": "Pools",
  "crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
  "features": [
    {
      "properties": {"prop0": "value0"},
      "type": "Feature",
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -96.8131837248802,
              33.0548974593963
            ],
            [
              -96.813183054328,
              33.0548974593963
            ],
            [
              -96.8131837248802,
              33.0548974593963
            ]
          ]
        ]
      }
    }
  ]
}
```
